### PR TITLE
Laravel 11.x Shift

### PR DESCRIPTION
**Pull request by georgeburdell**
This pull request includes the changes for upgrading to Laravel 11.x. Feel free to commit any additional changes to the `shift-120781` branch.

**Before merging**, you need to:

- Checkout the `shift-120781` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, try with `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts).

### CODE REVIEW

**Comment by georgeburdell** [comment]
:information_source: To slim down the Laravel installation, Laravel 11 no longer has most of the core files previously included in the default Laravel application. While you are welcome to publish and customize these files, they are no longer required.

Shift takes an iterative approach to removing core files which are not customized or where its customizations may be done elsewhere in a modern Laravel 11 application. As such, you may see some commits removing files and others _re-registering_ your customizations.

**Comment by georgeburdell** [comment]
:warning: The application bootstrapping changed in Laravel 11. As a result, files like `artisan` and `public/index.php` were rewritten. Shift [overwrote these files](https://github.com/RoboJackets/loop/pull/73/commits/a81cd68b5387a72afca0abcd937adc6f70717f5a?w=1) but detected yours may have contained customizations. You should review the diff to see if any of your customizations are still needed.

**Comment by georgeburdell** [comment]
:x: Shift could not upgrade the following files since they differed from the default Laravel version. You will need to compare these files against the [default Laravel 11 versions](https://github.com/laravel-shift/laravel-11.x/) and merge any changes:

- [ ] lang/en/validation.php

**Comment by georgeburdell** [comment]
:information_source: Laravel 11 no longer requires you to maintain the default configuration files. Your configuration [now merges with framework defaults](https://laravel-news.com/laravel11-streamlined-configs). 

Shift [streamlined your configuration files](https://github.com/RoboJackets/loop/pull/73/commits/7b0f7a5702fc438f39ea55f9694568ca47738f2b?w=1) by removing options that matched the Laravel defaults and preserving your _true customizations_. These are values which are not changeable through `ENV` variables.

If you wish to keep the full set of configuration files, Shift recommends running `artisan config:publish --all --force` to get the latest configuration files from Laravel 11, then reapplying the customizations Shift streamlined.

**Comment by georgeburdell** [comment]
:information_source: Shift detected customized options within your configuration files which may be set with an `ENV` variable. To help keep your configuration files streamlined, you may set the following variables. Be sure adjust any values per environment.

```txt
APP_TIMEZONE=America/New_York
AUTH_PASSWORD_RESET_TOKEN_TABLE=password_resets
BCRYPT_ROUNDS=10
CACHE_STORE=file
DB_CONNECTION=mysql
MAIL_MAILER=smtp
QUEUE_CONNECTION=sync
REDIS_QUEUE_RETRY_AFTER=600
SESSION_DRIVER=file
```

**Note:** some of these may simply be values which changed between Laravel 10 and Laravel 11. You may ignore any `ENV` variables you do not need to customize.

**Comment by georgeburdell** [comment]
:warning: The `BROADCAST_DRIVER`, `CACHE_DRIVER`, and `DATABASE_URL` environment variables were renamed in Laravel 11 to `BROADCAST_CONNECTION`, `CACHE_STORE`, and `DB_URL`, respectively.

Shift [automated this change](https://github.com/RoboJackets/loop/pull/73/commits/c4f8fc17bc1c8c50f027560bd3e85088e814e1e4?w=1) for your committed files, but you should review any additional locations where your environment is configured and update to the new variable names.

**Comment by georgeburdell** [comment]
:x: The `bootstrap/app.php` file has been completely rewritten in Laravel 11 to allow configuring your Laravel application in a single location. Shift [overwrote your file](https://github.com/RoboJackets/loop/pull/73/commits/045ab25c203872b5517d3249ebbb58d3f5fb0b22?w=1), but detected it may have contained customizations. You should review the diff to see if any of your customizations are still needed.

**Comment by georgeburdell** [comment]
:warning: Laravel 11 automatically discovers policies scanning your application's `Policies` directory at or above the directory containing your models.

Shift detected policies registered with the `policies` property of your `AuthServiceProvider`. If any of these policies can not be automatically discovered, you may register them manually using `Gate::policy()` in your `AppServiceProvider`.

**Comment by georgeburdell** [comment]
:x: The `app/Console/Kernel.php` file has been removed in Laravel 11. Shift [overwrote your file](https://github.com/RoboJackets/loop/pull/73/commits/a384255c1d38ac528fafb99f7d47c3463327a0ce?w=1), but detected it may have contained customizations. You should review the diff to see if any of your customizations are still needed. If so, you may re-apply them to the `routes/console.php` file or the new `bootstrap/app.php` file. [Review the documentation](https://laravel.com/docs/11.x/artisan#registering-commands) for additional details.

**Comment by georgeburdell** [comment]
:information_source: Shift [updated your dependencies](https://github.com/RoboJackets/loop/pull/73/commits/bd700021e8b27e29ad50e6e31dc5117004c2a4e8?w=1) for Laravel 11. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 11. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

The following dependencies were updated by a major version and may have their own changes. You may check their changelog for any additional upgrade steps.

- [ ] [barryvdh/laravel-ide-helper](https://packagist.org/packages/barryvdh/laravel-ide-helper)
- [ ] [laravel/sanctum](https://packagist.org/packages/laravel/sanctum)
- [ ] [laravel/slack-notification-channel](https://packagist.org/packages/laravel/slack-notification-channel)
- [ ] [sentry/sentry-laravel](https://packagist.org/packages/sentry/sentry-laravel)
- [ ] [spatie/laravel-permission](https://packagist.org/packages/spatie/laravel-permission)
- [ ] [subfission/cas](https://packagist.org/packages/subfission/cas)

**Comment by georgeburdell** [comment]
:information_source: Starting with Laravel 10, PHP type hints were added within classes included in a Laravel application. In an effort to modernize your code, Shift [automated this change](https://github.com/RoboJackets/loop/pull/73/commits/709fab87353939e0aadf56d766071caba66348f7?w=1) where Laravel strictly specifies a type. If you prefer not to type hint your code you may revert this commit by running: `git revert 709fab87`

**Comment by georgeburdell** [comment]
:warning: Many first-party Laravel packages no longer load their migrations automatically. Instead, you may need to publish their migrations to your application if you have not already done so. Shift detected you are using Sanctum. You may run the following command to publish their migrations:

```sh
php artisan vendor:publish --tag=sanctum-migrations
```

**Comment by georgeburdell** [comment]
:information_source: Laravel 11 now updates the timestamp when publishing vendor migrations. This may cause problems in existing applications when these migrations were previously published and ran with their default timestamp.

To preserve the original behavior, Shift disabled this feature in your `database.php` configuration file. If you do not have any vendor migrations or have squashed all of your existing migrations, you may re-enable the `update_date_on_publish` option. If this is the only customization within `database.php`, you may remove this configuration file.

**Comment by georgeburdell** [comment]
:warning: Previously, Laravel would append a colon (`:`) to any cache key prefix for DynamoDB, Memcache, or Redis. Laravel 11 no longer appends a colon to your cache key prefix. If you are using one of these stores, you should append a colon to your prefix to avoid invalidating your cache.

**Comment by georgeburdell** [comment]
:warning: Many of the default drivers changed in Laravel 11. For example, the default database driver is `sqlite` and the default cache store is `database`. If you experience errors setting up your environment, be sure you have properly set your `ENV` variables for these drivers. If you wish to adopt the new defaults, you may follow the documentation to set them up for your application.

**Comment by georgeburdell** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 7.0. Shift detected references to Symfony classes within your application. These are most likely type hints and can safely be ignored. If you are using Symfony classes directly or experience issues relating to Symfony, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/7.0/UPGRADE-7.0.md) for any additional changes.

**Comment by georgeburdell** [comment]
:warning: Laravel 11 now includes a database driver for MariaDB. Previously the MySQL driver offered parity with MariaDB. However, with MariaDB 10.1, there are more database specific features available. If you are using MariaDB, you may want to evaluate this new `mariadb` driver after completing your upgrade to Laravel 11.

**Comment by georgeburdell** [comment]
:warning: Shift detected you are using a Laravel package like Horizon or Nova which may need to have its published assets regenerated after upgrading. Be sure to use `artisan` to _republish_ these assets as well as `php artisan view:clear` to avoid any errors.

**Comment by georgeburdell** [comment]
:tada: Congratulations, you're now running the latest version of Laravel!

Next, you may optionally run the following _Shifts_ to ensure your application is fully upgraded, adopts the latest Laravel conventions, and easier to maintain in the future:

- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automatically updates your code to the latest Laravel conventions.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and configuration for your application.
- [CI Generator](https://laravelshift.com/ci-generator) intelligently generates CI jobs to lint PHP, check code style, and run tests, including Dusk.

You may also use the [Shift Workbench](https://laravelshift.com/workbench) to automate common tasks for maintaining your Laravel application.

**Review by kberzinch — APPROVED** [review]

**Pull request merged**
